# ALL_TASKS = ['agnews.py',
#              'climate_fever.py',
#              'ethos.py',
#              'dbpedia_14.py',
#              'financial_phrasebank.py',
#              'glue_mrpc.py',
#              'glue_rte.py',
#              'glue_sst2.py',
#              'glue_wnli.py',
#              'hate_speech18.py',
#              'imdb.py',
#              'medical_questions_pairs.py',
#              'poem_sentiment.py',
#              'rotten_tomatoes.py',
#              'sick.py',
#              'superglue_cb.py',
#              'trec.py',
#              'tweet_eval.py']

ALL_TASKS = ['trec.py']